baseurl: /
languageCode: en-US
title: "Omics: Love, Death & Code"
theme: hugo-lithium
disqus:
  Shortname: alfonsosaera
comments: "true"
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: https://github.com/alfonsosaera
    - name: LinkedIn
      url: https://www.linkedin.com/in/alfonso-saera-vila-6bb1a651/
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: Bioinformatics blog dedicated to new tools & applicactions, single-cell omics, AI, and multiomics.
  favicon: DNA_favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 50
    url: DNA.png
    width: 50
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
